### ISSUE TITLE
Add new memory stuff introduced in November update

### ISSUE THREAD

**Issue by orkaboy** [Eein/sea-of-stars-tas#103]
- [x] Multiple players
- [x] #144
- [x] #143
- [x] #136

**Comment by Eein** [comment]
a ton of new classes for SinglePlayerPlus
![image](https://github.com/user-attachments/assets/948f0809-64af-4eb2-9be9-75eab8adae26)

**Comment by Eein** [comment]
Items are fixed as well - new currency type plus a couple of items.
