### ISSUE TITLE
Load Game Screen

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#148]
routing would like to check if the load game screen is in memory.

**Comment by Eein** [comment]
This is in an ecs-based ui, and doesn't have references off the SaveGameManager or the TitleScreenManager

will have to generate a new save list when asked; will probably make this a request of the SaveDataManager so the seq can update it when it wants it.

`SaveGameManager::update_save_list()` or something. There will need to be some tooling made to select saves

**Comment by orkaboy** [comment]
Note, #150 implements a naive load game without memory usage. It seems to work good enough for now.
