### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by orkaboy** [Eein/sea-of-stars-tas#18]
Rust has a unified logging interface: https://github.com/rust-lang/log?tab=readme-ov-file#in-executables

Multiple backends are supported.

- https://docs.rs/colog/latest/colog/ is a pretty simple colored log to terminal.
- https://docs.rs/log4rs/latest/log4rs/ is a more complex framework with support for file + console.
- https://docs.rs/fern/latest/fern/ is a different complex framework with similar support. Has colored output (but some issues in v0.6 according to docs)

**Comment by orkaboy** [comment]
We can pick any one of these, and then use the `trace!`, `debug!`, `info!`, `warn!` and `error!` macros instead of `println!`

**Comment by Eein** [comment]
colog seems simple enough
i say we just go with that and if we need something crazier we can upgrade - with many loggers as long as windows supports the ansi codes it should be fine

**Comment by orkaboy** [comment]
Marking this one as completed for now. We can reopen if we decide on a different logger.
