### ISSUE TITLE
Title Sequence

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#31]
Add sequencer that can get through the speedrun beta title sequence and start a new game

- speedrun konami code may not be required on dlc, so dead reckoning is fine
- [x] #52
- [x] Put managers into `GameState`, accessible by `Sequencer`
- [x] #51
- [x] Add parameters (read from config in `GameState`)
- [x] `SeqTitleSequence` node
- [x] Integrate menu navigation with FSM

**Comment by orkaboy** [comment]
Marking this one as done for now, though I'll likely revisit the implementation.
