### ISSUE TITLE
Cutscenes (both skipping dialogue through button-mashing, skipping cutscenes with B-button and speedrun mode skipping).

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#33]

**Comment by orkaboy** [comment]
Potentially this is handled by the recently merged PR that added the cut scene handling to the game manager. Keeping it open until we've tested it in a few more situations.

**Comment by orkaboy** [comment]
From what I've seen so far, this works seamlessly in all situations (though in some special cases you need to grab control from it). Counting this as closed.
