### ISSUE TITLE
Joystick trigger buttons

### ISSUE THREAD

**Issue by orkaboy** [Eein/sea-of-stars-tas#42]
We need to add LT/RT to both joystick implementations, since these are used for both Live Mana and changing Time of Day. iirc at least with XINPUT these are handled differently than the other buttons, since they are analogue.

- [x] Add LT/RT to common interface
- [x] Add LT/RT to linux implementation
- [x] Add LT/RT to windows implementation

**Comment by orkaboy** [comment]
Technically we already have LT/RT in the common interface. If we're happy with just doing ON/OFF for them, we can tick off the first box. Not sure SoS even supports anything for the analogue input anyways.

**Comment by orkaboy** [comment]
Implemented for windows in #43

**Comment by Eein** [comment]
Also implemented for linux in #43 
This should be fully implemented
