### ISSUE TITLE
Combat Manager: Add additional fields to CombatEnemy

### ISSUE THREAD

**Issue by Eein** [Eein/sea-of-stars-tas#92]
its present! I'll prepare a secondary PR to get these additional fields added 
![image](https://github.com/user-attachments/assets/a2313d1a-8274-438e-912f-3f0de9f4c708)

_Originally posted by @Eein in https://github.com/Eein/sea-of-stars-tas/pull/90#discussion_r1807247173_

**Comment by orkaboy** [comment]
I see `damageTypeModifiers` there as well, vulnerabilities?

**Comment by orkaboy** [comment]
Also, what is `qualifiers`?

**Comment by Eein** [comment]
> Also, what is `qualifiers`?

![image](https://github.com/user-attachments/assets/428160e4-dbc6-4894-9788-3aa8a373b4f7)
no idea - will look next time i'm in here

**Comment by Eein** [comment]
> I see `damageTypeModifiers` there as well, vulnerabilities?

seems like it!

I'm guessing overrides is like Wyrd/Apparition changing them in battle. Will find out

**Comment by Eein** [comment]
damageTypeModifiers signature SerializableDictionary<EDamageType, float>
blocked by #94 

this is 4byte and 4byte stacked no skip
